### ISSUE TITLE
The worst release practice ever

### ISSUE THREAD

**Issue by onlyjob** [GabOpenSource/gab-social#3]
I did not think I would ever see release practice worse than Oracle's, but Gab managed to breach the lowest of the low in terms of source releases.  

Just a binary archive, committed to _git_ and not even an uncompressed source code tree?!? No changelog??

This is incompetent and disgraceful. Please improve!

**Comment by freespeech4ever** [comment]
This is entirely intentional, lol.  The license requirement of releasing it must be met, that is all.  Otherwise, zero interest.

**Comment by kjkrum** [comment]
@freespeech4ever He's saying unzip the archive so changes to individual files can be tracked. That's what git is good for.

BTW, did you get my email? You should move this repo to Gitlab. They have privacy options so people can report potential security issues directly to the maintainer.

**Comment by onlyjob** [comment]
> This is entirely intentional, lol. The license requirement of releasing it must be met, that is all. Otherwise, zero interest.

Intentional incompetence and no motivation to improve. Got it.  :(

**Comment by onlyjob** [comment]
@kjkrum FYI, they have moved this repository _from_ Gitlab. (Originally Gab had its own private Gitlab instance that they have refused to open for public even for issue management.)

**Comment by freespeech4ever** [comment]
You don't get it... We don't want it to be open source, we don't want issue management.  We don't want changes tracked.  Preferably, this would be closed source.  Security issues are to be reported via email.  
The license however requires some form of "release" which i will meet at the minimum level possible.  If you have an issue with that, who cares?

**Comment by kjkrum** [comment]
Imagine not wanting your program to be AGPL but then using AGPL dependencies and being bitter about it. LOL. LMAO even.

**Comment by freespeech4ever** [comment]
Peanut brain, imagine being stuck with a decision someone else made 7 years ago.

**Comment by kjkrum** [comment]
Stuck how? The company presumably owns the copyright on most of the code. If they removed and replaced whatever AGPL dependency is making the whole work AGPL, past versions would still be AGPL but future versions would not need to be.

**Comment by freespeech4ever** [comment]
It's too foundational, not a simple dependency.  A total rewrite has been imagined, intended, started, and abandoned several times.  It's not worth it, too many other things to be done.

**Comment by kjkrum** [comment]
If whoever wrote it released it under the AGPL, that doesn't constrain _them_ (or whoever owns the copyright now) to the AGPL. Sounds like you don't want any advice, though.

**Comment by freespeech4ever** [comment]
It's not that, you don't understand the dependencies.

**Comment by onlyjob** [comment]
Stop making excuses for incompetence, @freespeech4ever.
You're using fruits of collective, open source development by community, yet want to exclude community from development as much as possible?!? 
Working on "closed source" alone does not scale. Fix your paranoid trust issues and engage those who are still willing to help. Your ill attitude is very discouraging and future of Gab is not certain with anti open source, anti-community approach.

P.S. What is Open Source if not Free Speech in technology? Open Source 4ever!

**Comment by freespeech4ever** [comment]
No thanks!  We've never allowed community contribution to development afaik... We forked from the base 4+ years ago and haven't looked back, built everything ourselves. We are essentially a closed-source shop, and we manage well enough.

**Comment by kjkrum** [comment]
Well, since you ignored my email about a possible minor security issue, I'll just go ahead and override Github's push protection on my fork.
